/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package app.view;

import javax.swing.*;
import java.awt.*;

public class DashboardInternal extends javax.swing.JInternalFrame {

    // Componentes ACCESIBLES para el controlador
    public JLabel lblTotalProductos;
    public JLabel lblAlertas;
    public JLabel lblStockBajo;
    public JLabel lblPedidosPendientes;

    public JTextArea txtLotes;
    public JTextArea txtStockBajo;
    public JTextArea txtAltaDemanda;

    public DashboardInternal() {

        setTitle("Dashboard");
        setClosable(false);
        setMaximizable(false);
        setIconifiable(false);
        setResizable(false);
        setBorder(null);
        setSize(900, 650);

        JPanel main = new JPanel();
        main.setBackground(new Color(245, 245, 245));
        main.setLayout(new BoxLayout(main, BoxLayout.Y_AXIS));
        main.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));

        //-------------------------------------
        // TÍTULO
        //-------------------------------------
        JLabel title = new JLabel("Dashboard");
        title.setFont(new Font("Segoe UI", Font.BOLD, 26));
        title.setForeground(new Color(60, 60, 60));
        title.setAlignmentX(Component.LEFT_ALIGNMENT);

        main.add(title);
        main.add(Box.createVerticalStrut(20));

        //-------------------------------------
        // TARJETAS SUPERIORES (vacías)
        //-------------------------------------
        JPanel cards = new JPanel(new GridLayout(1, 4, 15, 0));
        cards.setOpaque(false);

        lblTotalProductos = new JLabel("—");
        lblAlertas = new JLabel("—");
        lblStockBajo = new JLabel("—");
        lblPedidosPendientes = new JLabel("—");

        cards.add(createCard("Total Productos", lblTotalProductos));
        cards.add(createCard("Alertas de Vencimiento", lblAlertas));
        cards.add(createCard("Stock Bajo", lblStockBajo));
        cards.add(createCard("Pedidos Pendientes", lblPedidosPendientes));

        main.add(cards);
        main.add(Box.createVerticalStrut(20));

        //-------------------------------------
        // SECCIONES (solo UI)
        //-------------------------------------
        txtLotes = new JTextArea();
        txtStockBajo = new JTextArea();
        txtAltaDemanda = new JTextArea();

        main.add(createSection("Lotes Próximos a Vencer", txtLotes));
        main.add(Box.createVerticalStrut(20));

        main.add(createSection("Stock Bajo", txtStockBajo));
        main.add(Box.createVerticalStrut(20));

        main.add(createSection("Alta Demanda", txtAltaDemanda));

        add(main);
    }

    // TARJETA (UI)
    private JPanel createCard(String title, JLabel dynamicLabel) {
        JPanel card = new JPanel();
        card.setBackground(Color.WHITE);
        card.setBorder(BorderFactory.createLineBorder(new Color(220, 220, 220), 1));
        card.setLayout(new BoxLayout(card, BoxLayout.Y_AXIS));
        card.setPreferredSize(new Dimension(150, 90));

        JLabel l1 = new JLabel(title);
        l1.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        l1.setForeground(new Color(90, 90, 90));

        dynamicLabel.setFont(new Font("Segoe UI", Font.BOLD, 22));
        dynamicLabel.setForeground(new Color(40, 40, 40));

        l1.setAlignmentX(Component.CENTER_ALIGNMENT);
        dynamicLabel.setAlignmentX(Component.CENTER_ALIGNMENT);

        card.add(Box.createVerticalStrut(10));
        card.add(l1);
        card.add(dynamicLabel);

        return card;
    }

    // SECCIÓN (UI)
    private JPanel createSection(String title, JTextArea area) {
        JPanel section = new JPanel();
        section.setBackground(Color.WHITE);
        section.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(new Color(220, 220, 220)),
                BorderFactory.createEmptyBorder(15, 15, 15, 15)
        ));
        section.setLayout(new BorderLayout());

        JLabel t = new JLabel(title);
        t.setFont(new Font("Segoe UI", Font.BOLD, 18));
        t.setForeground(new Color(60, 60, 60));

        area.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        area.setEditable(false);
        area.setBackground(Color.WHITE);
        area.setLineWrap(true);
        area.setWrapStyleWord(true);

        section.add(t, BorderLayout.NORTH);
        section.add(new JScrollPane(area), BorderLayout.CENTER);

        return section;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
